config_args = {
    'dataset': ('CUB', 'dataset name'),
    'device': ('cuda:0', ''),
    'emb': ('', 'embedding name'),
    'emb_dim': (50, 'embedding dimension'),
    'num_experts': (8, 'number of experts in MoE'),
    'margin': (0.1, 'margin for loss'),
    'margin1': (0.1, 'second margin for loss'),
    'weight': (0.01, 'weight for contrastive loss'),
    't': (0.5, 'temperature parameter'),
    'num_layers': (3, 'number of GCN layers'),
    'lr': (0.001, 'learning rate'),
    'batch_size': (4096, 'batch size'),
    'wd': (0.0005, 'weight decay'),
    'momentum': (0.95, 'momentum'),
    'max_norm': (1.5, 'max norm for projection'),
    'scale': (0.1, 'scale for initialization'),
    'seed': (1234, 'random seed'),
    'epochs': (100, 'number of epochs'),
    'eval_batch_num': (20, 'number of batches for evaluation'),
    'attSize': (312, 'attribute dimension for CUB'),
    'nclass_all': (200, 'total number of classes for CUB'),
    'nclass_seen': (150, 'number of seen classes for CUB'),
    'resSize': (2048, 'visual feature dimension')
}